-- Q.1 What is the total revenue generated by male vs female customers?

select gender, sum(purchase_amount) as revenue
from customer
group by gender

-- Q2. Which customers used a discount but still spent more than the average purchase amount?

Select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount > (select avg(purchase_amount) from customer)

-- Q.3 Which are the top 5 products with the highest average review rating?

select item_purchased ,Round(Avg(review_rating), 2) as " Average Product Rating"
from customer
group by item_purchased
order by Avg(review_rating) DESc
limit 5

-- compare the average Purchase Amounts between standard and Express Shipping.

select shipping_type , Round(Avg(purchase_amount), 2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

-- Q5. Do Subscribed spend more? compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status, 
count(customer_id) as total_customers,
Round(avg(purchase_amount), 2) as average_spend, 
Round(sum(purchase_amount), 2) as total_revenue
from customer
group by subscription_status
order by average_spend, total_revenue desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased,
Round(100 * sum(case when discount_applied = 'Yes' Then 1 else 0 end) /Count(*), 2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. segment customer into new, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.alter

With customer_type as (
select customer_id, previous_purchases,
case 
    When previous_purchases = 1 then 'New'
    When previous_purchases Between 2 and 10 then 'Returning'
    else 'Loyal'
    End as Customer_segment
from customer
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
Group by customer_segment

-- Q8. What are the top 3 most purchased products within each category

with item_counts as(
select category,item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category,item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- Q9. Are customer who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

-- Q10. What is the revenue contribution of each age group?

select age_group, sum(purchase_amount) as Total_revenue
from customer
group by age_group
order by Total_revenue desc;
